name: fartenbuch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_dotenv: ^5.2.1
  font_awesome_flutter: ^10.8.0
  google_maps_flutter: ^2.12.2
  http: ^1.4.0
  lottie: ^3.3.1
  supabase_flutter: ^2.9.0
  google_places_flutter: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/animation.json
  - assets/images/
  - assets/icons/
  - .env
  
